services: 
  backend:
      build: backend
      depends_on:
        database:
          condition: service_healthy
      env_file: "./backend/.env"
      ports:
        - "3000:3000"
  database:
      env_file: "./backend/.env"
      healthcheck:
        interval: 2s
        retries: 30
        timeout: 5s
        test: 'pg_isready --username=postgres --dbname=innercircle'
      image: postgres
      volumes:
        - ./data:/var/lib/postgresql/
  frontend:
      build: 
        context: frontend
        args:
          ENV: prod  # dev for localhost, prod for server
      ports:
        - "80:80"
      depends_on:
        - backend
      volumes:
        - ./uploads:/usr/share/nginx/html/uploads
